# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: 
  cd HomeStays
  npm install
  displayName: 'Installing dependencies'

- script: npm run build
  displayName: 'Building App'

# Save artifacts to refer them in release builds
- task: PublishPipelineArtifact@1
  inputs:
    path: $(Agent.BuildDirectory)/s/HomeStays/build
    artifact: HomeStays artifacts

