export const FETCHING= 'FETCHING';

export const FETCH_CARDS= 'FETCH_CARDS';

export const FETCH_CARDS_SUCCESS= 'FETCH_CARDS_SUCCESS';

export const FETCH_CARDS_ERROR= 'FETCH_CARDS_ERROR';

export const FETCH_CARD_DETAIL= 'FETCH_CARD_DETAIL';

export const FETCH_CARD_DETAIL_SUCCESS= 'FETCH_CARD_DETAIL_SUCCESS';

export const FETCH_CARD_DETAIL_ERROR= 'FETCH_CARD_DETAIL_ERROR';
